replicaCount: 3

ingress:
    logging:
        level: info
    health_port: 7888
    prometheus_port: 7889
    http_relay_port: 9090
    rtmp_port: 1935
    whip_port: 8080
    rtc_config:
        use_external_ip: true
        udp_port: 7885
    redis:
        address: ${aws_redis_cluster}
        username: ${livekit_redis_username}
        password: ${livekit_redis_password}
        use_tls: false
    cpu_cost:
        rtmp_cpu_cost: 2
        whip_cpu_cost: 2
        whip_bypass_transcoding_cpu_cost: 0.1

loadBalancer:
    servicePort: 7888
    annotations: {}

terminationGracePeriodSeconds: 3600

autoscaling:
    enabled: false

resources:
    requests:
        cpu: 500m
        memory: 512Mi
    limits:
        cpu: 1000m
        memory: 1024Mi

serviceAccount:
    create: true
    annotations: {}
    name: ""

podHostNetwork: true

podAnnotations:
    sidecar.istio.io/inject: "false"
    linkerd.io/inject: disabled

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}