replicaCount: 3

egress:
    log_level: info
    health_port: 8080
    prometheus_port: 9090
    api_key: ${livekit_api_key}
    api_secret: ${livekit_api_secret}
    ws_url: wss://${livekit_domain_name}:7880
    redis:
        address: ${aws_redis_cluster}
        username: ${livekit_redis_username}
        password: ${livekit_redis_password}
        use_tls: false

terminationGracePeriodSeconds: 3600

autoscaling:
    enabled: false

resources:
    requests:
        cpu: 500m
        memory: 512Mi
    limits:
        cpu: 1000m
        memory: 1024Mi

serviceAccount:
    create: true
    annotations: {}
    name: ""

podAnnotations:
    sidecar.istio.io/inject: "false"
    linkerd.io/inject: disabled

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}