name: 'Terraform-DEMO-No-Destroy'

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_FILE: ../../environments/demo/terraform.tfvars

jobs:
  terraform:
    name: 'Terraform DEMO No Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: tf

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace
        run: |
          WORKSPACE=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

      - name: Terraform Plan
        run: terraform plan -var-file ${{ env.TF_VAR_FILE }} -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Show
        run: terraform show