name: 'Terraform-On-Demand'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Application environment to use'
        required: true
        default: 'demo'
      aws-region:
        description: 'AWS region to use'
        required: true
        default: 'us-east-1'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_VAR_FILE: terraform.tfvars

jobs:
  terraform:
    name: 'Terraform On-Demand'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "~>1.9.0"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -lock=false

      - name: Terraform Workspace
        run: |
          WORKSPACE="default-aws-infra-${{ github.event.inputs.environment }}-${{ github.event.inputs.aws-region }}"
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -var-file ${{ env.TF_VAR_FILE }} -out=tfplan -lock=false

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan -lock=false

      - name: Terraform Show
        run: terraform show

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file ${{ env.TF_VAR_FILE }} -lock=false