name: 'Terraform-DEMO-Only-Destroy-Everyday'

on:
  schedule:
    - cron: '42 0 * * *'
  workflow_dispatch:  # Allow manual triggering

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_FILE: terraform.tfvars

jobs:
  terraform:
    name: 'Terraform DEMO Only Destroy Everyday'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: environments/demo

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: |
          terraform version
          terraform init

      - name: Terraform Destroy
        run: |
          for ws in $(terraform workspace list | grep -oP '(?<=\s)refs-\S+' || true)
          do
            echo "Processing workspace: $ws"
            terraform workspace select "$ws" || continue
            terraform init || continue
            terraform destroy -auto-approve -var-file ${{ env.TF_VAR_FILE }} || echo "Failed to destroy workspace: $ws"
          done
        continue-on-error: true

      - name: Cleanup Workspaces
        run: |
          for ws in $(terraform workspace list | grep -oP '(?<=\s)refs-\S+' || true)
          do
            echo "Cleaning up workspace: $ws"
            terraform workspace select default
            terraform workspace delete "$ws" || echo "Failed to delete workspace: $ws"
          done
        continue-on-error: true