name: 'Terraform-DEMO-Only-Destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Application environment to use'
        required: true
        default: 'demo'
      aws-region:
        description: 'AWS region to use'
        required: true
        default: 'us-east-1'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_VAR_FILE: terraform.tfvars

jobs:
  terraform:
    name: 'Terraform DEMO Only Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "~>1.9.0"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -lock=false

      - name: Terraform Workspace
        run: |
          WORKSPACE="default-aws-infra-${{ github.event.inputs.environment }}-${{ github.event.inputs.aws-region }}"
          terraform workspace select "$WORKSPACE" || (echo "Workspace $WORKSPACE does not exist" && exit 1)

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file ${{ env.TF_VAR_FILE }} -out=tfdestroyplan -lock=false

      - name: Terraform Destroy
        run: terraform apply -lock=false -auto-approve tfdestroyplan

      - name: Cleanup Workspace
        if: success()
        run: |
          terraform workspace select default
#          terraform workspace delete "default-aws-infra-${{ github.event.inputs.environment }}-${{ github.event.inputs.aws-region }}"