name: 'Terraform'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  TF_CLOUD_ORGANIZATION: "10xR"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "your-workspace-name"
  CONFIG_DIRECTORY: "."

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan_run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan_output
        with:
          plan: ${{ fromJSON(steps.plan_run.outputs.payload).data.relationships.plan.data.id }}

      - name: Update PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan Output
            \`\`\`
            ${{ steps.plan_output.outputs.stdout }}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Apply Run
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        with:
          run: ${{ fromJSON(steps.plan_run.outputs.payload).data.id }}
          comment: "Apply run from GitHub Actions CI"