name: 'Terraform-On-Demand'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Application environment to use'
        required: true
        default: 'demo'
      aws-region:
        description: 'AWS region to use'
        required: true
        default: 'us-east-1'

env:
  TF_CLOUD_ORGANIZATION: "10xR"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "environments/${{ github.event.inputs.environment }}"

jobs:
  terraform:
    name: 'Terraform On-Demand'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: "default-aws-infra-${{ github.event.inputs.environment }}-${{ github.event.inputs.aws-region }}"
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan_run
        with:
          workspace: "default-aws-infra-${{ github.event.inputs.environment }}-${{ github.event.inputs.aws-region }}"
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - name: Apply Run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        with:
          run: ${{ fromJSON(steps.plan_run.outputs.payload).data.id }}
          comment: "Apply run from GitHub Actions On-Demand workflow"

      - name: Show Outputs
        run: |
          terraform show